App\Entity\Libro:
  attributes:
    id:
      groups: ['libro']
    titulo:
      groups: ['libro']
    anyo:
      groups: ['libro']
    autor:
      groups: ['libro']
    categoria:
      groups: ['libro']